### ISSUE TITLE
Issue building

### ISSUE THREAD

**Issue by javierggt** [sot/cxotime#20]
I get this error when building in centos 7 image:

```
cxotime/parse_times.c: In function 'parse_int_from_char_array':
cxotime/parse_times.c:52:9: error: 'for' loop initial declarations are only allowed in C99 mode
         for (int i = idx0; i <= idx1; i++) {
         ^
cxotime/parse_times.c:52:9: note: use option -std=c99 or -std=gnu99 to compile your code
```

I guess this should go in here: https://github.com/sot/cxotime/blob/master/setup.py#L17

**Comment by taldcroft** [comment]
Yes, just add that as a compile arg.  I had this same problem with the astropy version of this, but in that case it was only showing up in the 32-bit linux compilation.  It got fixed with: https://github.com/astropy/astropy/pull/10360/commits/77b9937894e1aecaff17608fadc0a7ca33d1330a. So just copying the latest parse_times.c from the astropy PR is an option. Eventually this local version for CxoTime will get dropped in favor of the astropy-supplied one.

**Comment by javierggt** [comment]
I thought the solution would be to add the flag to the build. I mean: changing the code actually makes it worse. Things like initializing the variables are a good idea, and the declaration within the loop scope is also good. Still... if we will always mirror what is in astropy, then I will just copy that. I also do not know what issues would arise by adding the flag.

**Comment by javierggt** [comment]
Tha file does not seem to exist in astropy master (?)
